# Generated by Django 5.2.5 on 2026-09-09 22:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('number', models.CharField(blank=True, db_index=True, editable=False, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('new', 'Order in'), ('fire', 'Firing'), ('ready', 'Ready'), ('served', 'Served'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=9)),
                ('channel', models.CharField(choices=[('dinein', 'Dine-in'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery'), ('pickup', 'Pickup'), ('web', 'Web order')], db_index=True, default='dinein', max_length=9)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('rush', 'Rush'), ('vip', 'VIP')], default='normal', max_length=6)),
                ('guest_name', models.CharField(blank=True, default='Guest', max_length=80)),
                ('party_size', models.PositiveSmallIntegerField(default=2)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('service_total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=220)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='accounts.staffprofile')),
                ('guest_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.staffprofile')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('message', models.TextField(blank=True, max_length=400)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='orders.order')),
            ],
            options={
                'verbose_name': 'guest note',
                'verbose_name_plural': 'guest notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name_at_order', models.CharField(max_length=90)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('cooking', 'Cooking'), ('ready', 'Ready'), ('served', 'Served'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=9)),
                ('course', models.PositiveSmallIntegerField(default=1, help_text='1 starter · 2 main · 3 sweet')),
                ('notes', models.CharField(blank=True, max_length=180)),
                ('is_comp', models.BooleanField(default=False)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='menu.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
            ],
            options={
                'verbose_name': 'ticket line',
                'verbose_name_plural': 'ticket lines',
                'ordering': ['course', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('qr', 'QR / wallet'), ('comp', 'Comp'), ('split', 'Split')], default='card', max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.staffprofile')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('label', models.CharField(help_text='T-01', max_length=12, unique=True)),
                ('seats', models.PositiveSmallIntegerField(default=2)),
                ('zone', models.CharField(choices=[('main', 'Main room'), ('terrace', 'Terrace'), ('bar', 'Bar'), ('private', 'Private')], default='main', max_length=8)),
                ('status', models.CharField(choices=[('free', 'Free'), ('seated', 'Seated'), ('ordered', 'Ordered'), ('running', 'Running'), ('dessert', 'Dessert'), ('settling', 'Settling'), ('clearing', 'Clearing')], db_index=True, default='free', max_length=9)),
                ('x', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Floor coordinate (metres).', max_digits=5)),
                ('y', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('rotation', models.PositiveSmallIntegerField(default=0, help_text='Degrees, used by the 3D floor.')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'floor plan',
                'ordering': ['zone', 'label'],
                'indexes': [models.Index(fields=['zone', 'status'], name='idx_table_zone_state')],
                'constraints': [models.CheckConstraint(condition=models.Q(('seats__gte', 1)), name='table_has_seats')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.table'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='idx_order_status_time'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['channel', 'status'], name='idx_order_channel_state'),
        ),
    ]
