# Generated by Django 5.2.5 on 2026-09-09 22:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('blurb', models.CharField(blank=True, max_length=160)),
                ('accent', models.CharField(default='#D8B26A', max_length=9)),
                ('icon', models.CharField(default='✦', help_text='One glyph — used as the chapter mark.', max_length=6)),
                ('service_order', models.PositiveSmallIntegerField(db_index=True, default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'menu chapter',
                'verbose_name_plural': 'menu chapters',
                'ordering': ['service_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('file', models.ImageField(upload_to='uploads/menu/%Y/%m/')),
                ('label', models.CharField(blank=True, help_text='Shown in the library picker.', max_length=90)),
                ('checksum', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('bytes', models.PositiveIntegerField(default=0, help_text='File size in bytes.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.CharField(blank=True, max_length=180)),
                ('source', models.CharField(choices=[('upload', 'Uploaded'), ('seed', 'Studio library'), ('scan', 'Imported')], default='upload', max_length=6)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photo library',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(db_index=True, max_length=90)),
                ('match_key', models.CharField(db_index=True, editable=False, help_text='Normalised name used for smart matching.', max_length=90)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='Was-price; drives the struck-through offer.', max_digits=8, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('par_level', models.PositiveSmallIntegerField(default=24, help_text='Target level the smart restock nudges you to.')),
                ('low_stock_threshold', models.PositiveSmallIntegerField(default=6)),
                ('unit', models.CharField(default='portions', max_length=12)),
                ('photo_source', models.CharField(choices=[('none', 'No photo'), ('upload', 'Uploaded now'), ('library', 'Picked from library'), ('inherited', 'Auto-inherited from a twin dish')], default='none', editable=False, max_length=9)),
                ('photo_note', models.CharField(blank=True, editable=False, max_length=140)),
                ('station', models.CharField(choices=[('garde', 'Garde manger'), ('saute', 'Sauté'), ('grill', 'Grill'), ('tandoor', 'Tandoor'), ('pastry', 'Pastry'), ('bar', 'Bar')], default='saute', max_length=8)),
                ('prep_minutes', models.PositiveSmallIntegerField(default=14)),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('protein_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_veg', models.BooleanField(default=False, verbose_name='vegetarian')),
                ('is_vegan', models.BooleanField(default=False)),
                ('heat', models.PositiveSmallIntegerField(default=0, help_text='0–3 chilli marks.')),
                ('is_signature', models.BooleanField(default=False, verbose_name='signature dish')),
                ('is_seasonal', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True, verbose_name='on the menu')),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('pairs_with', models.JSONField(blank=True, default=list, help_text='Names of dishes that upsell well with this one.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sold_total', models.PositiveIntegerField(default=0, editable=False)),
                ('last_sold_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes_added', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='menu.category')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.photo')),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
                'ordering': ['category__service_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.CharField(default='adjustment', max_length=24)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='menu.item')),
            ],
            options={
                'verbose_name': 'price change',
                'verbose_name_plural': 'price ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('ADJUST', 'Adjust')], db_index=True, default='IN', max_length=6)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(choices=[('sale', 'Sold'), ('restock', 'Restock'), ('waste', 'Waste / spoil'), ('comp', 'Comped'), ('count', 'Stock count'), ('86', "86'd"), ('seed', 'Opening balance')], default='restock', max_length=8)),
                ('reference', models.CharField(blank=True, help_text='Order number, invoice, delivery slip…', max_length=24)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_moves', to='menu.item')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_available'], name='idx_dish_chapter_avail'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-price'], name='idx_dish_price'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-last_sold_at'], name='idx_dish_last_sold'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('category', 'match_key'), name='uniq_dish_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0'))), name='price_not_negative'),
        ),
        migrations.AddIndex(
            model_name='pricechange',
            index=models.Index(fields=['item', '-created_at'], name='idx_price_item_time'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', '-created_at'], name='idx_stock_item_time'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['direction', 'reason'], name='idx_stock_dir_reason'),
        ),
    ]
