# Generated by Django 5.2.5 on 2026-09-09 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('display_name', models.CharField(max_length=80)),
                ('handle', models.SlugField(blank=True, max_length=40, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('chef', 'Chef'), ('sous', 'Sous chef'), ('waiter', 'Server'), ('cashier', 'Cashier'), ('barista', 'Barista')], db_index=True, default='waiter', max_length=8)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('pin', models.CharField(blank=True, help_text='4–6 digit floor/kiosk code.', max_length=6)),
                ('accent', models.CharField(default='#D8B26A', max_length=9)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('clocked_in_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.CharField(blank=True, max_length=24)),
                ('tables_owned', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=180)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'team member',
                'verbose_name_plural': 'team',
                'ordering': ['role', 'display_name'],
                'indexes': [models.Index(fields=['role', 'is_on_duty'], name='idx_staff_role_duty')],
            },
        ),
    ]
