# Generated by Django 5.2.5 on 2026-09-09 22:54

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(default='Lumière', max_length=90)),
                ('tagline', models.CharField(blank=True, default='Fire, salt & patience.', max_length=160)),
                ('accent', models.CharField(default='#D8B26A', help_text='Brand gold as hex.', max_length=9)),
                ('accent_soft', models.CharField(default='#F0DCB0', max_length=9)),
                ('currency_symbol', models.CharField(default='$', max_length=4)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('7.50'), max_digits=5)),
                ('service_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('service_style', models.CharField(choices=[('table', 'Table service'), ('counter', 'Counter / bar'), ('mixed', 'Mixed floor')], default='mixed', max_length=12)),
                ('address', models.CharField(blank=True, default='14 Harbor Lane, Riverside District', max_length=200)),
                ('phone', models.CharField(blank=True, default='+1 202 555 0142', max_length=32)),
                ('email', models.EmailField(blank=True, default='hello@lumiere.dining', max_length=254)),
                ('opens_at', models.TimeField(default=datetime.time(11, 30))),
                ('closes_at', models.TimeField(default=datetime.time(23, 30))),
                ('days_open', models.JSONField(blank=True, default=list, help_text='0=Mon … 6=Sun')),
                ('kitchen_lane_minutes', models.PositiveSmallIntegerField(default=16)),
                ('low_stock_default', models.PositiveSmallIntegerField(default=6)),
                ('receipt_footer', models.CharField(blank=True, default='Thank you — see you tomorrow.', max_length=160)),
                ('is_open_override', models.BooleanField(default=False, verbose_name='force open')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurant profile',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('deleted', 'deleted'), ('restocked', 'restocked'), ('priced', 'repriced'), ('served', 'served'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('eighty-sixed', "86'd"), ('imaged', 'photographed'), ('signed-in', 'signed in')], db_index=True, default='updated', max_length=14)),
                ('table', models.CharField(blank=True, db_index=True, help_text='Logical table, e.g. menu_item', max_length=40)),
                ('object_id', models.CharField(blank=True, max_length=24)),
                ('message', models.CharField(max_length=220)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(choices=[('info', 'info'), ('good', 'good'), ('warn', 'warn'), ('bad', 'bad')], default='info', max_length=5)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('moment', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'activity entry',
                'verbose_name_plural': 'activity ledger',
                'ordering': ['-moment'],
                'indexes': [models.Index(fields=['table', 'object_id'], name='idx_activity_target')],
            },
        ),
    ]
