# Generated by Django 5.2.5 on 2025-09-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Fastfood', 'Fastfood'), ('Juice & Drinks', 'Juice & Drinks')], max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
